apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
spec:
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: yashpimple22/reddit-clone
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: helloservice
spec:
  selector:
    app: helloservice
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  type: NodePort
